# Common kafka broker environment variables
x-kafka-broker-env: &kafka-broker-env
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
  KAFKA_JMX_HOSTNAME: localhost
  KAFKA_ENABLE_KRAFT: yes
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093,2@broker-2:29093"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  KAFKA_METADATA_LOG_DIR: "/var/lib/kafka/metadata"
  CLUSTER_ID: "MTkwSDkzMDg5KTdFNDJCRU"

# Common kafka broker configuration
x-kafka-broker-common: &kafka-broker-common
  image: confluentinc/cp-kafka:7.7.0
  extra_hosts:
    - "host.docker.internal:host-gateway"

# Common kafka connect environment variables
x-kafka-connect-env: &kafka-connect-env
  CONNECT_BOOTSTRAP_SERVERS: "broker:29092,broker-2:29092"
  CONNECT_GROUP_ID: compose-connect-group
  CONNECT_OFFSET_FLUSH_INTERVAL_MS: 500
  CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 2
  CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 2
  CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 2
  CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
  CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema_registry:8081
  CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.5.3-0.jar
  CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
  CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
  CONNECT_ERRORS_RETRY_TIMEOUT: 90000
  CONNECT_ERRORS_RETRY_DELAY_MAX_MS: 120000
  CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars,/usr/share/confluent-hub-components"

# Common kafka connect configuration
x-kafka-connect-common: &kafka-connect-common
  image: confluentinc/cp-kafka-connect:7.7.0
  depends_on:
    - broker-1
    - broker-2
    - schema_registry
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./kafka-connect-plugins:/etc/kafka-connect/jars

name: "Kafka-KRaft-Cluster-TimescaleDB"
services:
  # Replaced QuestDB with TimescaleDB
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    hostname: timescaledb
    container_name: rta_timescaledb
    restart: always
    ports:
      - "5888:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kafka_db
    volumes:
      - ./timescaledb/data:/var/lib/postgresql/data:rw
    networks:
      - kafka_network

  broker-1:
    <<: *kafka-broker-common
    hostname: broker
    container_name: rta_kafka_broker
    ports:
      - "9092:9092"
      - "9101:9101"
    volumes:
      - ./broker-1/kafka-data:/var/lib/kafka/data
      - ./broker-1/kafka-metadata:/var/lib/kafka/metadata
      - ./broker-1/kafka-secrets:/etc/kafka/secrets
    environment:
      <<: *kafka-broker-env
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_JMX_PORT: 9101
      KAFKA_LISTENERS: "PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092"
    networks:
      - kafka_network

  broker-2:
    <<: *kafka-broker-common
    hostname: broker-2
    container_name: rta_kafka_broker_2
    ports:
      - "9093:9093"
      - "9102:9102"
    volumes:
      - ./broker-2/kafka-data:/var/lib/kafka/data
      - ./broker-2/kafka-metadata:/var/lib/kafka/metadata
      - ./broker-2/kafka-secrets:/etc/kafka/secrets
    environment:
      <<: *kafka-broker-env
      KAFKA_NODE_ID: 2
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-2:29092,PLAINTEXT_HOST://localhost:9093"
      KAFKA_JMX_PORT: 9102
      KAFKA_LISTENERS: "PLAINTEXT://broker-2:29092,CONTROLLER://broker-2:29093,PLAINTEXT_HOST://0.0.0.0:9093"
    networks:
      - kafka_network

  schema_registry:
    image: confluentinc/cp-schema-registry:7.7.0
    hostname: schema_registry
    container_name: rta_schema_registry
    depends_on:
      - broker-1
      - broker-2
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "broker:29092,broker-2:29092"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,OPTIONS"
    networks:
      - kafka_network

  kafka-connect-1:
    <<: *kafka-connect-common
    hostname: kafka-connect
    container_name: rta_kafka_connect
    ports:
      - "8083:8083"
    environment:
      <<: *kafka-connect-env
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_LISTENERS: http://0.0.0.0:8083
    networks:
      - kafka_network
    command:
      - bash
      - -c
      - |
        echo "Installing Confluent JDBC Connector..."
        confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest

        # Launch Kafka Connect
        /etc/confluent/docker/run &
        #
        # Wait for Kafka Connect listener
        echo "Waiting for Kafka Connect to start listening on localhost â³"
        while : ; do
          curl_status=$$(curl -s -o /dev/null -w %{http_code} http://localhost:8083/connectors)
          echo -e $$(date) " Kafka Connect listener HTTP state: " $$curl_status " (waiting for 200)"
          if [ $$curl_status -eq 200 ] ; then
            break
          fi
          sleep 5
        done

        echo -e "\n--\n+> Registering TimescaleDB (JDBC) Connector"

        curl -s -X PUT -H "Content-Type:application/json" http://localhost:8083/connectors/timescaledb-trades/config -d '{
            "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
            "tasks.max": "5",
            "topics": "trades",
            "connection.url": "jdbc:postgresql://timescaledb:5432/kafka_db",
            "connection.user": "postgres",
            "connection.password": "password",
            "dialect.name": "PostgreSqlDatabaseDialect",
            "insert.mode": "insert",
            "auto.create": "true",
            "auto.evolve": "true",
            "table.name.format": "trades",
            "value.converter": "io.confluent.connect.avro.AvroConverter",
            "value.converter.schema.registry.url": "http://schema_registry:8081",
            "key.converter": "org.apache.kafka.connect.storage.StringConverter"
        }'

        sleep infinity

  kafka-connect-2:
    <<: *kafka-connect-common
    hostname: kafka-connect-2
    container_name: rta_kafka_connect_2
    ports:
      - "8084:8084"
    environment:
      <<: *kafka-connect-env
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect-2
      CONNECT_LISTENERS: http://0.0.0.0:8084
    networks:
      - kafka_network
    command:
      - bash
      - -c
      - |
        echo "Installing Confluent JDBC Connector..."
        confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest
        
        # Launch Kafka Connect
        /etc/confluent/docker/run

networks:
  kafka_network:
    driver: bridge